import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"
import { Toaster } from "react-hot-toast"

import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Optional: to use as a CSS variable
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Toaster position="bottom-center" />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
